word_list = []
word_list.append(input("Type in a word ending in 'ing'"))
word_list.append(input("Type in a word ending in 'ing'"))
word_list.append(input("Type in a place:"))
word_list.append(input("Type in a place:"))
word_list.append(input("Type in a popular person: "))
word_list.append(input("Type in what you would ask your popular person':"))
word_list.append(input("What would your popular person say to you':"))
word_list.append(input("He said this to you because:"))
word_list.append(input("What was behind the door:"))
word_list.append(input("What did the underground passage way lead to':"))
word_list.append(input("What did you hear:"))

print("One day I was %s" % word_list[0])
print("And suddenly it started to %s" % word_list[1])
print("And because of this i had to go to the  %s" % word_list[2])
print("When i got to the  %s" % word_list[3])
print("I Found my idol  %s" % word_list[4])
print("So I ask him/her  %s" % word_list[5])
print("Before i finished asking my question he look at me and said  %s" % word_list[6])
print("He said this to me because he look outside the window and saw  %s" % word_list[7])
print("He said to follow him quickly and suddenly he opened a door and behind it was  %s" % word_list[8])
print("Because of what was behind the door we went to an underground passage way that lead to  %s" % word_list[9])
print("While looking in the underground passage we found a door so we decided to try to open it but suddenly "
      "we heard %s" % word_list[10])
print("when we heard the loud noise i woke up and realized it was all a dream")
