verb1 = input("Type in a word ending in 'ing': ")
verb2 = input("Type in a word ending in 'ing': ")
noun1 = input("Type in a place: ")
noun2 = input("Type in a place: ")
noun3 = input("Type in a popular person: ")
noun4 = input("Type in what you would ask your popular person':")
noun5 = input("What would your popular person say to you':")
noun6 = input("He said this to you because:")
noun7 = input("What was behind the door:")
noun8 = input("What did the underground passage way lead to':")
noun9 = input("What did you hear:")
print("One day I was %s" % verb1)
print("And suddenly it started to %s" % verb2)
print("And because of this i had to go to the  %s" % noun1)
print("When i got to the  %s" % noun2)
print("I Found my idol  %s" % noun3)
print("So I ask him/her  %s" % noun4)
print("Before i finished asking my question he look at me and said  %s" % noun5)
print("He said this to me because he look outside the window and saw  %s" % noun6)
print("He said to follow him quickly and suddenly he opened a door and behind it was  %s" % noun7)
print("Because of what was behind the door we went to an underground passage way that lead to  %s" % noun8)
print("While looking in the underground passage we found a door so we decided to try to open it but suddenly "
      "we heard %s" % noun9)
print("when we heard the loud noice i woke up and realized it was all a dream")
